<a href="https://colab.research.google.com/github/amit306/machineLearning/blob/main/CustomNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import numpy as np
# Basic Neural network class
class neuralNetwork:

  def __init__(self,input,hidden,output,learning_rate):
    self.input = input
    self.hidden = hidden
    self.output = output
    self.learning_rate = learning_rate
    ## from input to hidden layer
    self.weights1 = np.random.uniform(-1, 1, (self.input, self.hidden))
    # from hidden to output layer
    self.weights2 = np.random.uniform(-1, 1, (self.hidden, self.output))

  def _sigmoid(self, x):
    return 1 / (1 + np.exp(-x))

  def train(self,x,y):
    # Forward pass
    # Input to hidden layer
    hidden_inputs = np.dot(x, self.weights1)
    hidden_outputs = self._sigmoid(hidden_inputs)

    # Hidden to output layer
    final_inputs = np.dot(hidden_outputs, self.weights2)
    final_outputs = self._sigmoid(final_inputs)

    # Calculate error
    output_errors = y - final_outputs

    # Backpropagation
    # Output layer error gradient
    output_error_gradient = output_errors * final_outputs * (1 - final_outputs)

    # Update weights between hidden and output layers
    self.weights2 += self.learning_rate * np.dot(hidden_outputs.T, output_error_gradient)

    # Hidden layer error
    hidden_errors = np.dot(output_error_gradient, self.weights2.T)

    # Hidden layer error gradient
    hidden_error_gradient = hidden_errors * hidden_outputs * (1 - hidden_outputs)

    # Update weights between input and hidden layers
    self.weights1 += self.learning_rate * np.dot(x.T, hidden_error_gradient)

  def predict(self,x):
    # Forward pass for prediction
    hidden_inputs = np.dot(x, self.weights1)
    hidden_outputs = self._sigmoid(hidden_inputs)

    final_inputs = np.dot(hidden_outputs, self.weights2)
    final_outputs = self._sigmoid(final_inputs)
    return final_outputs

  def query():
    pass

In [3]:
myNN = neuralNetwork(3,15,3,0.015)

In [4]:
# Training data: Larger and more diverse dataset
# Generate 10,000 random samples, each with 3 features (values between 0 and 1)
n_samples = 10000
x_train = np.random.rand(n_samples, 3)
y_train = x_train.copy() # For replication task, y_train is the same as x_train

print(f"Generated {n_samples} training samples.")
print("First 5 Training Inputs (x_train):\n", x_train[:5])
print("\nFirst 5 Target Outputs (y_train):\n", y_train[:5])

Generated 10000 training samples.
First 5 Training Inputs (x_train):
 [[0.64530298 0.02188582 0.0901321 ]
 [0.78807229 0.6018858  0.41111329]
 [0.08311199 0.89746693 0.48520705]
 [0.36595342 0.9923073  0.14548927]
 [0.10674621 0.59457316 0.35173215]]

First 5 Target Outputs (y_train):
 [[0.64530298 0.02188582 0.0901321 ]
 [0.78807229 0.6018858  0.41111329]
 [0.08311199 0.89746693 0.48520705]
 [0.36595342 0.9923073  0.14548927]
 [0.10674621 0.59457316 0.35173215]]


In [5]:
epochs = 10000000
for i in range(epochs):
    # Pick a random training example
    index = np.random.randint(len(x_train))
    input_data = x_train[index:index+1]
    target_data = y_train[index:index+1]

    myNN.train(input_data, target_data)

    if i % (epochs/1000) == 0: # Print progress every 0.1% of epochs
        # Make a prediction on the entire training set to calculate overall error
        predictions = myNN.predict(x_train)
        mse = np.mean(np.square(y_train - predictions))
        print(f"\n--- Epoch {i+1}/{epochs} --- MSE: {mse:.8f} ---")

print(f"\n--- Final Training Step after {epochs} epochs ---")
# Run one last training step on a full batch to get final MSE
predictions = myNN.predict(x_train)
mse = np.mean(np.square(y_train - predictions))
print(f"Final MSE after {epochs} epochs: {mse:.8f}")


--- Epoch 1/10000000 --- MSE: 0.17994910 ---

--- Epoch 10001/10000000 --- MSE: 0.04203681 ---

--- Epoch 20001/10000000 --- MSE: 0.01846675 ---

--- Epoch 30001/10000000 --- MSE: 0.00892944 ---

--- Epoch 40001/10000000 --- MSE: 0.00510875 ---

--- Epoch 50001/10000000 --- MSE: 0.00339296 ---

--- Epoch 60001/10000000 --- MSE: 0.00254795 ---

--- Epoch 70001/10000000 --- MSE: 0.00207896 ---

--- Epoch 80001/10000000 --- MSE: 0.00181285 ---

--- Epoch 90001/10000000 --- MSE: 0.00165353 ---

--- Epoch 100001/10000000 --- MSE: 0.00155051 ---

--- Epoch 110001/10000000 --- MSE: 0.00148367 ---

--- Epoch 120001/10000000 --- MSE: 0.00143839 ---

--- Epoch 130001/10000000 --- MSE: 0.00140626 ---

--- Epoch 140001/10000000 --- MSE: 0.00138281 ---

--- Epoch 150001/10000000 --- MSE: 0.00136479 ---

--- Epoch 160001/10000000 --- MSE: 0.00134915 ---

--- Epoch 170001/10000000 --- MSE: 0.00133720 ---

--- Epoch 180001/10000000 --- MSE: 0.00132670 ---

--- Epoch 190001/10000000 --- MSE: 0.0013164

In [6]:
print("Weights from input to hidden layer:\n", myNN.weights1)
print("\nWeights from hidden to output layer:\n", myNN.weights2)

Weights from input to hidden layer:
 [[-1.03205956 -0.26755432  1.10178763 -0.99996013  1.16579923  0.22432003
   0.00273637  0.15158093  0.01839985 -0.51332492 -0.62881683 -0.31147967
   0.51935924  0.35499926  0.47417979]
 [ 0.71085099  0.67536094 -1.0862901  -0.23976061 -0.09377466  0.41826492
  -0.96395719  0.19575685  1.06102664 -0.56845234 -0.09349628 -0.90929613
   0.71772744 -0.95812024  0.39483338]
 [ 0.78954511 -1.00468029  0.19914402  0.35176071 -1.1072781   0.78584036
  -0.07299143  0.97158443 -1.11944021 -0.23953843 -0.610687    0.3682331
  -0.12791319 -0.46682594  0.55450989]]

Weights from hidden to output layer:
 [[-2.02324313  2.29789259  2.96612192]
 [-1.02712826  1.42482603 -3.27708247]
 [ 4.28895484 -2.32317462  1.21182902]
 [-4.97194765 -1.55523126 -0.2293447 ]
 [ 2.47123695 -0.48797954 -3.00871209]
 [ 0.45438558  0.84443863  1.53219569]
 [-0.9780587  -3.71528938 -0.72516081]
 [ 0.69155603  0.47035544  2.87310181]
 [-0.38582956  2.13902524 -3.52465111]
 [-2.1817191

In [7]:
# Test data
test_input = np.array([[0.7, 0.2, 0.4],
                       [0.3, 0.8, 0.68]])

print("Test Input:\n", test_input)

# Make predictions
predictions = myNN.predict(test_input)

print("\nPredictions:\n", predictions)

Test Input:
 [[0.7  0.2  0.4 ]
 [0.3  0.8  0.68]]

Predictions:
 [[0.7364312  0.18387981 0.38352914]
 [0.27513328 0.81398364 0.71260257]]


In [8]:
print("Training Inputs (x_train/y_train):\n", x_train)
print("\nPredictions for Training Data:\n", myNN.predict(x_train))
print("\nDifference (y_train - predictions):\n", y_train - myNN.predict(x_train))

print("\n---")

print("Test Input:\n", test_input)
print("\nPredictions for Test Input:\n", myNN.predict(test_input))

Training Inputs (x_train/y_train):
 [[0.64530298 0.02188582 0.0901321 ]
 [0.78807229 0.6018858  0.41111329]
 [0.08311199 0.89746693 0.48520705]
 ...
 [0.98058386 0.69498992 0.56257181]
 [0.9341223  0.61499281 0.47953546]
 [0.5606368  0.13917037 0.14390314]]

Predictions for Training Data:
 [[0.67006447 0.08215454 0.11278121]
 [0.81030295 0.62444268 0.39740349]
 [0.1163217  0.87249168 0.4794778 ]
 ...
 [0.91214698 0.71549379 0.57482026]
 [0.89478678 0.63446467 0.4774222 ]
 [0.57902516 0.13933171 0.14314114]]

Difference (y_train - predictions):
 [[-0.02476149 -0.06026871 -0.02264911]
 [-0.02223066 -0.02255688  0.0137098 ]
 [-0.03320971  0.02497525  0.00572925]
 ...
 [ 0.06843687 -0.02050387 -0.01224845]
 [ 0.03933552 -0.01947185  0.00211325]
 [-0.01838836 -0.00016133  0.000762  ]]

---
Test Input:
 [[0.7  0.2  0.4 ]
 [0.3  0.8  0.68]]

Predictions for Test Input:
 [[0.7364312  0.18387981 0.38352914]
 [0.27513328 0.81398364 0.71260257]]
